sudo: required

services:
  - docker

script:
  - docker build --tag micro-klix .

after_script:
  - docker images
  - docker login -u=$DOCKER_USERNAME -p=$HEROKU_API_KEY registry.heroku.com
  - docker tag micro-klix registry.heroku.com/micro-klix/web
  - docker push registry.heroku.com/micro-klix/web

before_deploy: npm install heroku --no-save

deploy:
  - provider: script
    script: heroku container:release web
    skip_cleanup: true
    on:
      master: true
